export const PERMISSIONS = {
  USERS: {
    CREATE: { name: 'Create User', slug: 'users.create', description: 'Allows creating new users.' },
    READ: { name: 'View Users', slug: 'users.read', description: 'Allows viewing user information.' },
    UPDATE: { name: 'Update User', slug: 'users.update', description: 'Allows updating user information.' },
    DELETE: { name: 'Delete User', slug: 'users.delete', description: 'Allows deleting users.' },
    ASSIGN: { name: 'Manage Roles', slug: 'users.manage_roles', description: 'Allows assigning and revoking roles for users.' },
  },
  ROLES: {
    CREATE: { name: 'Create Role', slug: 'roles.create', description: 'Allows creating new roles.' },
    READ: { name: 'View Roles', slug: 'roles.read', description: 'Allows viewing role information.' },
    UPDATE: { name: 'Update Role', slug: 'roles.update', description: 'Allows updating role information.' },
    DELETE: { name: 'Delete Role', slug: 'roles.delete', description: 'Allows deleting roles.' },
    ASSIGN: { name: 'Manage Permissions', slug: 'roles.manage_permissions', description: 'Allows assigning and revoking permissions for roles.' },
  },
  PERMISSIONS: {
    // CREATE: { name: 'Create Permission', slug: 'permissions.create', description: 'Allows creating new permissions.' },
    READ: { name: 'View Permissions', slug: 'permissions.read', description: 'Allows viewing available permissions.' },
    // UPDATE: { name: 'Update Permission', slug: 'permissions.update', description: 'Allows updating permission information.' },
    // DELETE: { name: 'Delete Permission', slug: 'permissions.delete', description: 'Allows deleting permissions.' },
  },
  PRODUCTS: {
    CREATE: { name: 'Create Product', slug: 'products.create', description: 'Allows creating new products.' },
    READ: { name: 'View Products', slug: 'products.read', description: 'Allows viewing product information.' },
    UPDATE: { name: 'Update Product', slug: 'products.update', description: 'Allows updating product information.' },
    DELETE: { name: 'Delete Product', slug: 'products.delete', description: 'Allows deleting products.' },
  },
  DATA_UPLOAD: {
    DAILY_VALUATION_CREATE: { name: 'Upload Daily Valuations', slug: 'data_upload.daily_valuation.create', description: 'Allows uploading daily valuations.' },
    HOLDING_CREATE: { name: 'Upload Holdings', slug: 'data_upload.holding.create', description: 'Allows uploading holdings.' },
    MARKET_LIST_CREATE: { name: 'Upload Market List', slug: 'data_upload.market_list.create', description: 'Allows uploading market list.' },
    TRANSACTION_CREATE: { name: 'Upload Transactions', slug: 'data_upload.transaction.create', description: 'Allows uploading transactions.' },
    INDEX_HISTORY_CREATE: { name: 'Upload Index History', slug: 'data_upload.index_history.create', description: 'Allows uploading index history.' },
    DAILY_VALUATION_READ: { name: 'View Daily Valuations', slug: 'data_upload.daily_valuation.read', description: 'Allows viewing daily valuations.' },
    HOLDING_READ: { name: 'View Holdings', slug: 'data_upload.holding.read', description: 'Allows viewing holdings.' },
    MARKET_LIST_READ: { name: 'View Market List', slug: 'data_upload.market_list.read', description: 'Allows viewing market list.' },
    TRANSACTION_READ: { name: 'View Transactions', slug: 'data_upload.transaction.read', description: 'Allows viewing transactions.' },
    INDEX_HISTORY_READ: { name: 'View Index History', slug: 'data_upload.index_history.read', description: 'Allows viewing index history.' },
  },
  MASTERS: {
    ASSET_CLASS_CREATE: { name: 'Create Asset Class', slug: 'asset_class.create', description: 'Allows creating asset classes.' },
    ASSET_CLASS_READ: { name: 'View Asset Classes', slug: 'asset_class.read', description: 'Allows viewing asset classes.' },
    ASSET_CLASS_UPDATE: { name: 'Update Asset Class', slug: 'asset_class.update', description: 'Allows updating asset classes.' },
    ASSET_CLASS_DELETE: { name: 'Delete Asset Class', slug: 'asset_class.delete', description: 'Allows deleting asset classes.' },
    BENCHMARK_CREATE: { name: 'Create Benchmark', slug: 'benchmark.create', description: 'Allows creating benchmarks.' },
    BENCHMARK_READ: { name: 'View Benchmarks', slug: 'benchmark.read', description: 'Allows viewing benchmarks.' },
    BENCHMARK_UPDATE: { name: 'Update Benchmark', slug: 'benchmark.update', description: 'Allows updating benchmarks.' },
    BENCHMARK_DELETE: { name: 'Delete Benchmark', slug: 'benchmark.delete', description: 'Allows deleting benchmarks.' },
    FUND_MANAGER_CREATE: { name: 'Create Fund Manager', slug: 'fund_manager.create', description: 'Allows creating fund managers.' },
    FUND_MANAGER_READ: { name: 'View Fund Managers', slug: 'fund_manager.read', description: 'Allows viewing fund managers.' },
    FUND_MANAGER_UPDATE: { name: 'Update Fund Manager', slug: 'fund_manager.update', description: 'Allows updating fund managers.' },
    FUND_MANAGER_DELETE: { name: 'Delete Fund Manager', slug: 'fund_manager.delete', description: 'Allows deleting fund managers.' },
    CATEGORY_CREATE: { name: 'Create Category', slug: 'category.create', description: 'Allows creating categories.' },
    CATEGORY_READ: { name: 'View Categories', slug: 'category.read', description: 'Allows viewing categories.' },
    CATEGORY_UPDATE: { name: 'Update Category', slug: 'category.update', description: 'Allows updating categories.' },
    CATEGORY_DELETE: { name: 'Delete Category', slug: 'category.delete', description: 'Allows deleting categories.' },
  },
  SCHEMES: {
    CREATE: { name: 'Create Scheme', slug: 'schemes.create', description: 'Allows creating schemes.' },
    READ: { name: 'View Schemes', slug: 'schemes.read', description: 'Allows viewing schemes.' },
    UPDATE: { name: 'Update Scheme', slug: 'schemes.update', description: 'Allows updating schemes.' },
    DELETE: { name: 'Delete Scheme', slug: 'schemes.delete', description: 'Allows deleting schemes.' },
  },
  AMC: {
    CREATE: { name: 'Create Amc', slug: 'amc.create', description: 'Allows creating amc.' },
    READ: { name: 'View Amc', slug: 'amc.read', description: 'Allows viewing amc.' },
    UPDATE: { name: 'Update Amc', slug: 'amc.update', description: 'Allows updating amc.' },
    DELETE: { name: 'Delete Amc', slug: 'amc.delete', description: 'Allows deleting amc.' },
  },
};
