// Global Drizzle Client Token
export const DRIZZLE_PROVIDER = 'DRIZZLE_PROVIDER';

// Repository Tokens (Abstraction Contracts)
// Feature modules will use these to request the concrete repository.
export const USERS_REPOSITORY_TOKEN = Symbol('USERS_REPOSITORY');
export const ROLES_REPOSITORY_TOKEN = Symbol('ROLES_REPOSITORY');
export const PERMISSIONS_REPOSITORY_TOKEN = Symbol('PERMISSIONS_REPOSITORY');
export const PRODUCTS_REPOSITORY_TOKEN = Symbol('PRODUCTS_REPOSITORY');
export const FUNDS_REPOSITORY_TOKEN = Symbol('FUNDS_REPOSITORY');
export const ASSET_CLASSES_REPOSITORY_TOKEN = Symbol('ASSET_CLASSES_REPOSITORY');
export const BENCHMARK_INDICES_REPOSITORY_TOKEN = Symbol('BENCHMARK_INDICES_REPOSITORY');
export const FUND_MANAGERS_REPOSITORY_TOKEN = Symbol('FUND_MANAGERS_REPOSITORY');
export const CATEGORIES_REPOSITORY_TOKEN = Symbol('CATEGORIES_REPOSITORY');
export const SCHEMES_REPOSITORY_TOKEN = Symbol('SCHEMES_REPOSITORY');
export const DATA_UPLOAD_REPOSITORY_TOKEN = Symbol('DATA_UPLOAD_REPOSITORY');
